variable "availability_zone" {}
variable "env" {}
variable "subnet_cidr_block" {}
variable "vpc_cidr_block" {}
variable "allowed_ips" {}
variable "all_ips" {}
variable "instance_type" {}
variable "public_key_location" {}
variable "private_key_location" {}
variable "image_name" {}
